# Control file for continuous integration testing at http://travis-ci.org/

language: c

matrix:
  include:
    - os: linux
      compiler: clang
      env: USE_CONFIG=no
    - os: linux
      compiler: gcc
      env: USE_CONFIG=no
    # An unoptimised C99 build, for detecting non-static inline functions
    - os: linux
      compiler: gcc
      env: CFLAGS="-std=gnu99 -O0" USE_CONFIG=no
    - os: osx
      compiler: clang
      env: USE_CONFIG=no
    # Test the configure script
    - os: linux
      compiler: gcc
      env: USE_CONFIG=yes
    - os: osx
      compiler: clang
      env: USE_CONFIG=yes
    # An optimised build with address, leak and undefined behavior checking
    - os: linux
      compiler: clang
      sudo: required
      env: CFLAGS="-fsanitize=address" LDFLAGS="-fsanitize=address" USE_CONFIG=yes

env:
  global:
    - HTSDIR=./htslib

# For linux systems
addons:
  apt:
    packages:
    - liblzma-dev
    - libbz2-dev
    - libgsl0-dev

# For MacOSX systems
before_install:
  - |
    # Removing GSL dependant parts as they are not tested anyway
    # if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    #   brew update && \
    #   brew install xz gsl
    # fi

before_script:
  # Clone samtools/htslib (or another repository, as specified by a Travis CI
  # repository $HTSREPO setting) and check out a corresponding branch with the
  # same name, if any, or otherwise the default branch.
  - .travis/clone ${HTSREPO:-git://github.com/samtools/htslib.git} $HTSDIR $TRAVIS_BRANCH

script: |
  if test "$USE_CONFIG" = "yes"; then
    ( cd "$HTSDIR" && autoreconf ) && \
    autoreconf && \
    ./configure && \
    make && \
    make test
  else
    make plugindir=$TRAVIS_BUILD_DIR/plugins -e && \
    make -e test-plugins
  fi
